#pragma once

// WLJ ToDo: sort out converting this to an enum class 
enum XACT_WAVEBANK_AUDIOBANK : unsigned int
{
    XACT_WAVEBANK_AUDIOBANK_MUSIC01 = 0,
    XACT_WAVEBANK_AUDIOBANK_COINSFX = 1,
    XACT_WAVEBANK_AUDIOBANK_IMPACTSFX1 = 2,
};

#define XACT_WAVEBANK_AUDIOBANK_ENTRY_COUNT 3

